services:
  - type: web
    name: web-scraper-app
    env: node
    buildCommand: npm install && npm install puppeteer --no-sandbox --ignore-scripts
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
